import { makeStyles } from '@griffel/react';

export const useConcertinaListItemStyles = makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    borderBottomWidth: '0.0625rem',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    paddingTop: '1.2rem',
    paddingBottom: '0',
    paddingLeft: '0',
    paddingRight: '0',
  },
  heading: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    borderTopStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    borderRightStyle: 'none',
    backgroundColor: 'transparent',
    paddingTop: '0',
    paddingBottom: '0',
    paddingLeft: '0',
    paddingRight: '0',
    cursor: 'pointer',
    justifyContent: 'space-between',
  },
  title: {
    width: '100%',
    maxWidth: '600px',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 'auto',
    paddingTop: '0',
    paddingBottom: '0',
    paddingLeft: '0',
    paddingRight: '1.2rem',
    textAlign: 'left',
    fontWeight: 'var(--font-weight-medium)',
    fontSize: 'var(--font-size-small)',
    letterSpacing: '-0.01rem',
    color: 'var(--color-text)',
    whiteSpace: 'nowrap',
    overflowY: 'hidden',
    overflowX: 'hidden',
    textOverflow: 'ellipsis',
  },
  content: {
    width: '100%',
    paddingTop: '1.2rem',
    paddingBottom: '0',
    paddingLeft: '0',
    paddingRight: '0',
  },
  toggle: {
    width: '20px',
    height: '24px',
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: 'auto',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',

    '& svg': {
      transitionProperty: 'transform',
      transitionDuration: 'var(--transition-duration)',
      transitionTimingFunction: 'var(--transition-timing-function)',

      '& path': {
        fill: 'var(--color-tertiary)',
      },
    },
  },
  toggleExpanded: {
    transform: 'rotate(180deg)',
  },
  toggleIdle: {
    transform: 'rotate(0deg)',
  },
});
