/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/accordion/src/accordion-item/accordion-item.tsx',
  description: '',
  displayName: 'AccordionItem',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer-provided class name.',
      name: 'className',
      declarations: [
        {
          fileName:
            'arbutus/components/accordion/src/accordion-item/accordion-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    title: {
      defaultValue: null,
      description: 'The title of the accordion item that renders in the trigger.',
      name: 'title',
      declarations: [
        {
          fileName:
            'arbutus/components/accordion/src/accordion-item/accordion-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: 'string',
      },
    },
    initial: {
      defaultValue: {
        value: 'collapsed',
      },
      description: 'Initial state of the accordion item.',
      name: 'initial',
      declarations: [
        {
          fileName:
            'arbutus/components/accordion/src/accordion-item/accordion-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: '"collapsed" | "expanded"',
      },
    },
  },
};

export default propsDoc;
