/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/action-list-tile/src/action-list-item/action-list-item.tsx',
  description: '',
  displayName: 'ActionListItem',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-item/action-list-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    label: {
      defaultValue: null,
      description: 'Action label.',
      name: 'label',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-item/action-list-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: 'string',
      },
    },
    description: {
      defaultValue: null,
      description:
        "Concise action description for assistive technology (e.g. 'download', 'open link').",
      name: 'description',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-item/action-list-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: 'string',
      },
    },
    iconName: {
      defaultValue: null,
      description: 'Selection of icons.',
      name: 'iconName',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-item/action-list-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: '"arrow-right" | "chevron-right" | "full-screen" | "slide-in" | "slide-out" | "check" | "code" | "copy" | "download" | "exclamation" | "link" | "moon" | "open" | "sun" | "x"',
      },
    },
    onClick: {
      defaultValue: null,
      description: 'Click handler.',
      name: 'onClick',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-item/action-list-item.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: '(e?: SyntheticEvent<Element, Event>) => void',
      },
    },
  },
};

export default propsDoc;
