/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath:
    '../../components/action-list-tile/src/action-list-header/action-list-header.tsx',
  description: '',
  displayName: 'ActionListHeader',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-header/action-list-header.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    title: {
      defaultValue: null,
      description: 'Text that describes the collection of actions in the tile.',
      name: 'title',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-header/action-list-header.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: 'string',
      },
    },
    iconSrc: {
      defaultValue: null,
      description: 'Custom optional icon.',
      name: 'iconSrc',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-header/action-list-header.types.ts',
          name: 'TypeLiteral',
        },
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-header/action-list-header.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    iconAlt: {
      defaultValue: null,
      description: 'Accessible icon description.',
      name: 'iconAlt',
      declarations: [
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-header/action-list-header.types.ts',
          name: 'TypeLiteral',
        },
        {
          fileName:
            'arbutus/components/action-list-tile/src/action-list-header/action-list-header.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
  },
};

export default propsDoc;
