/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/badge/src/badge/badge.tsx',
  description: '',
  displayName: 'Badge',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName: 'arbutus/components/badge/src/badge/badge.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    color: {
      defaultValue: {
        value: 'primary',
      },
      description: 'Selection of color options.',
      name: 'color',
      declarations: [
        {
          fileName: 'arbutus/components/badge/src/badge/badge.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'ColorVariant',
      },
    },
    iconName: {
      defaultValue: null,
      description: 'Selection of icons.',
      name: 'iconName',
      declarations: [
        {
          fileName: 'arbutus/components/badge/src/badge/badge.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: '"arrow-right" | "chevron-right" | "full-screen" | "slide-in" | "slide-out" | "check" | "code" | "copy" | "download" | "exclamation" | "link" | "moon" | "open" | "sun" | "x"',
      },
    },
    isInline: {
      defaultValue: null,
      description: 'Sets the Badge to be an inline element.',
      name: 'isInline',
      declarations: [
        {
          fileName: 'arbutus/components/badge/src/badge/badge.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'boolean',
      },
    },
  },
};

export default propsDoc;
