/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/icon/src/icon/icon.tsx',
  description: '',
  displayName: 'Icon',
  methods: [],
  props: {
    iconName: {
      defaultValue: null,
      description: 'Selection of icons.',
      name: 'iconName',
      declarations: [
        {
          fileName: 'arbutus/components/icon/src/icon/icon.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: '"arrow-right" | "chevron-right" | "full-screen" | "slide-in" | "slide-out" | "check" | "code" | "copy" | "download" | "exclamation" | "link" | "moon" | "open" | "sun" | "x"',
      },
    },
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName: 'arbutus/components/icon/src/icon/icon.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    color: {
      defaultValue: {
        value: 'primary',
      },
      description: 'Selection of color options.',
      name: 'color',
      declarations: [
        {
          fileName: 'arbutus/components/icon/src/icon/icon.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'ColorVariant',
      },
    },
    size: {
      defaultValue: {
        value: 'medium',
      },
      description: 'Selection of size options.',
      name: 'size',
      declarations: [
        {
          fileName: 'arbutus/components/icon/src/icon/icon.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: '"small" | "medium" | "large"',
      },
    },
    label: {
      defaultValue: null,
      description:
        'Description of the icon for assistive technology. No label hides the icon from assistive technology\n(applicable for purely decorative elements).',
      name: 'label',
      declarations: [
        {
          fileName: 'arbutus/components/icon/src/icon/icon.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    isInline: {
      defaultValue: null,
      description: 'Sets the Icon to be an inline element.',
      name: 'isInline',
      declarations: [
        {
          fileName: 'arbutus/components/icon/src/icon/icon.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'boolean',
      },
    },
  },
};

export default propsDoc;
