/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/logo/src/logo/logo.tsx',
  description: '',
  displayName: 'Logo',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName: 'arbutus/components/logo/src/logo/logo.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    logoName: {
      defaultValue: null,
      description: 'Selection of logos.',
      name: 'logoName',
      declarations: [
        {
          fileName: 'arbutus/components/logo/src/logo/logo.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: '"figma" | "storybook"',
      },
    },
    size: {
      defaultValue: {
        value: 'fill',
      },
      description: 'Selection of size options.',
      name: 'size',
      declarations: [
        {
          fileName: 'arbutus/components/logo/src/logo/logo.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: '"small" | "medium" | "large" | "fill"',
      },
    },
    isInline: {
      defaultValue: null,
      description: 'Sets the Icon to be an inline element.',
      name: 'isInline',
      declarations: [
        {
          fileName: 'arbutus/components/logo/src/logo/logo.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'boolean',
      },
    },
    label: {
      defaultValue: null,
      description: 'Accessible label for the logo.',
      name: 'label',
      declarations: [
        {
          fileName: 'arbutus/components/logo/src/logo/logo.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
  },
};

export default propsDoc;
