/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/mark-list/src/mark-list/mark-list.tsx',
  description: '',
  displayName: 'MarkList',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName: 'arbutus/components/mark-list/src/mark-list/mark-list.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    iconName: {
      defaultValue: null,
      description: 'Selection of icons.',
      name: 'iconName',
      declarations: [
        {
          fileName: 'arbutus/components/mark-list/src/mark-list/mark-list.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: '"arrow-right" | "chevron-right" | "full-screen" | "slide-in" | "slide-out" | "check" | "code" | "copy" | "download" | "exclamation" | "link" | "moon" | "open" | "sun" | "x"',
      },
    },
    iconColor: {
      defaultValue: null,
      description: 'Selection of icon color options.',
      name: 'iconColor',
      declarations: [
        {
          fileName: 'arbutus/components/mark-list/src/mark-list/mark-list.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'ColorVariant',
      },
    },
  },
};

export default propsDoc;
