/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/resource-chip/src/resource-chip/resource-chip.tsx',
  description: '',
  displayName: 'ResourceChip',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName:
            'arbutus/components/resource-chip/src/resource-chip/resource-chip.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    text: {
      defaultValue: null,
      description: 'Resource name',
      name: 'text',
      declarations: [
        {
          fileName:
            'arbutus/components/resource-chip/src/resource-chip/resource-chip.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: true,
      type: {
        name: 'string',
      },
    },
    actionIconName: {
      defaultValue: {
        value: 'link',
      },
      description:
        'Selection of icons for indicating the type of action when the user clicks on ResourceChip.',
      name: 'actionIconName',
      declarations: [
        {
          fileName:
            'arbutus/components/resource-chip/src/resource-chip/resource-chip.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: '"arrow-right" | "chevron-right" | "full-screen" | "slide-in" | "slide-out" | "check" | "code" | "copy" | "download" | "exclamation" | "link" | "moon" | "open" | "sun" | "x"',
      },
    },
    onClick: {
      defaultValue: null,
      description: 'Click handler.',
      name: 'onClick',
      declarations: [
        {
          fileName:
            'arbutus/components/resource-chip/src/resource-chip/resource-chip.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: '() => void',
      },
    },
    size: {
      defaultValue: {
        value: 'medium',
      },
      description: 'Size of the button.',
      name: 'size',
      declarations: [
        {
          fileName:
            'arbutus/components/resource-chip/src/resource-chip/resource-chip.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'SizeKey',
      },
    },
    logoName: {
      defaultValue: null,
      description: 'Selection of logos that represent the resource type.',
      name: 'logoName',
      declarations: [
        {
          fileName:
            'arbutus/components/resource-chip/src/resource-chip/resource-chip.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: '"figma" | "storybook"',
      },
    },
    logoLabel: {
      defaultValue: null,
      description: 'Accessible label for the logo that represents the resource type.',
      name: 'logoLabel',
      declarations: [
        {
          fileName:
            'arbutus/components/resource-chip/src/resource-chip/resource-chip.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
  },
};

export default propsDoc;
