/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/tabs/src/tab-panels/tab-panels.tsx',
  description: '',
  displayName: 'TabPanels',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: '',
      name: 'className',
      declarations: [
        {
          fileName: '../../components/tabs/src/tab-panels/tab-panels.tsx',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
  },
};

export default propsDoc;
