/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

const propsDoc: PropsDoc = {
  tags: {},
  filePath: '../../components/tabs/src/tabs/tabs.tsx',
  description: '',
  displayName: 'Tabs',
  methods: [],
  props: {
    className: {
      defaultValue: null,
      description: 'Consumer provided class.',
      name: 'className',
      declarations: [
        {
          fileName: 'arbutus/components/tabs/src/tabs/tabs.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'string',
      },
    },
    initialIndex: {
      defaultValue: {
        value: '0',
      },
      description: 'Optional initial open tab',
      name: 'initialIndex',
      declarations: [
        {
          fileName: 'arbutus/components/tabs/src/tabs/tabs.types.ts',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: {
        name: 'number',
      },
    },
  },
};

export default propsDoc;
