import type { PropsDoc } from '@microsoft/arbutus.prop-docs-cli';

export type PropTableProps = {
  /**
   * Consumer provided class.
   */
  className?: string;

  /**
   * A component from the manifest generated by the `@microsoft/arbutus.prop-docs-cli`.
   */
  propsDoc: PropsDoc;

  /**
   * Caption for the table.
   */
  caption?: string;
};
