/**
 * THIS IS AN AUTOGENERATED FILE. ALL CHANGES WILL BE LOST.
 */
export default {
  tags: {},
  filePath: 'components/prop-table/__dev__/demo-component/demo-component.tsx',
  description: '',
  displayName: 'DemoComponent',
  methods: [],
  props: {
    className: {
      defaultValue: { value: 'undefined' },
      description: 'The className of the component.',
      name: 'className',
      declarations: [
        {
          fileName:
            'arbutus/components/prop-table/__dev__/demo-component/demo-component.types.tsx',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: { name: 'string' },
    },
    text: {
      defaultValue: { value: 'Hello' },
      description: 'The text of the component.',
      name: 'text',
      declarations: [
        {
          fileName:
            'arbutus/components/prop-table/__dev__/demo-component/demo-component.types.tsx',
          name: 'TypeLiteral',
        },
      ],
      required: false,
      type: { name: 'string' },
    },
  },
};
